import React from 'react';
import {UserProvider} from '@auth0/nextjs-auth0/client';
import type {Metadata} from 'next';
import {Rubik as font} from 'next/font/google';
import './globals.css';

const rubik = font({
	weight: '400',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app.',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang='en'>
			<UserProvider>
				<body className={rubik.className}>{children}</body>
			</UserProvider>
		</html>
	);
}
