import React from 'react';
import {UserProvider} from '@auth0/nextjs-auth0/client';
import {GlobalStateProvider} from '@/app/context';
import {getSession} from '@auth0/nextjs-auth0';
import Link from 'next/link';
import type {Metadata} from 'next';
import {Rubik as font} from 'next/font/google';
import './globals.css';

const rubik = font({
	weight: '400',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app.',
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
	const session = await getSession();
	return (
		<html lang='en'>
			<UserProvider>
				<body className={rubik.className}>
					<header>
						{session?.user && (
							<div>
								{session.user.email}
								<a className='flex flex-col items-center' href='/api/auth/logout'>
									Logout
								</a>
							</div>
						)}
						<Link href='/basket' className='flex  flex-col items-center'>
							Basket
						</Link>
					</header>
					<GlobalStateProvider>
						<main>{children}</main>
					</GlobalStateProvider>
				</body>
			</UserProvider>
		</html>
	);
}
